version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     secrets:
       - wp_mysql_root_password
       - wp_mysql_user
       - wp_mysql_password
     environment:
       MYSQL_ROOT_PASSWORD: /var/run/wp_mysql_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: /var/run/wp_mysql_user
       MYSQL_PASSWORD: /var/run/wp_mysql_password
     networks:
       - wordpress
     deploy:
       mode: replicated
       replicas: 1
       update_config:
         parallelism: 1
         delay: 10s
         #order: stop-first
       restart_policy:
         condition: on-failure

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     networks:
       - traefik-public
       - wordpress
     secrets:
       - wp_mysql_user
       - wp_mysql_password
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: /var/run/wp_mysql_user
       WORDPRESS_DB_PASSWORD: /var/run/wp_mysql_password
       WORDPRESS_DB_NAME: wordpress

     deploy:
       mode: replicated
       replicas: 1
       update_config:
         parallelism: 1
         delay: 10s
         #order: stop-first
       restart_policy:
         condition: on-failure
       labels:
         - "traefik.enable=true"
         - "traefik.http.routers.blog-http.rule=Host(`blog.fabianvolkers.com`)"
         - "traefik.http.routers.blog-http.entrypoints=web"
         - "traefik.http.routers.blog-http.middlewares=redirect-web-to-websecure@internal"
         - "traefik.http.routers.blog-https.rule=Host(`blog.fabianvolkers.com`)"
         - "traefik.http.routers.blog-https.entrypoints=websecure"
         - "traefik.http.routers.blog-https.tls=true"
         #- "traefik.http.routers.blog-https.service=api@internal"
         - "traefik.http.routers.blog-https.tls.certresolver=le"
         - "traefik.http.services.blog.loadbalancer.server.port=80"
volumes:
    db_data:

secrets:
    wp_mysql_root_password:
        external: true
    wp_mysql_user:
        external: true
    wp_mysql_password:
        external: true

networks:
    traefik-public:
        external: true
    wordpress:
