global:
    scrape_interval:     15s # By default, scrape targets every 15 seconds.
    # Attach these labels to any time series or alerts when communicating with
    # external systems (federation, remote storage, Alertmanager).
    external_labels:
      monitor: 'fabis-monitor'
  
scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']

    - job_name: 'plex'
      scrape_interval: 20s
      scrape_timeout: 15s
      static_configs:
        - targets: ['plex-exporter.fabianvolkers.com', 'movies.dyndns.fabianvolkers.com:9100']

    - job_name: 'fritzbox'
      scrape_interval: 20s
      scrape_timeout: 15s
      static_configs:
        - targets: ['movies.dyndns.fabianvolkers.com:8765']

    - job_name: 'grafana'
      scrape_interval: 10s
      static_configs:
        - targets: ['grafana.fabianvolkers.com']

    - job_name: 'servers'
      scrape_interval: 10s
      static_configs:
        - targets: ['93.95.228.112:9100', '167.71.57.253:9100', '134.122.73.133:9100', '34.107.6.242:9100']
