version: "3.3"
services:
  traefik:
    image: traefik:latest
    #privileged: true
    #command:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme:/etc/traefik/acme/
    networks:
      - traefik-public
    ports:
      - 80:80
      - 443:443
      #- target: 8080
      #  published: 8080
      #  mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        #order: stop-first
      restart_policy:
        condition: on-failure
      labels:
        #- "traefik.http.middlewares.auth.basicauth.users=traefik_admin:$1$bkAbZCTU$fEclEpGV5teqc0C18hk0V0"
        - "traefik.enable=true"
        - "traefik.http.routers.api-http.rule=Host(`traefik.fabianvolkers.com`)"
        - "traefik.http.routers.api-http.entrypoints=web"
        - "traefik.http.routers.api-http.middlewares=redirect-web-to-websecure@internal"
        - "traefik.http.routers.api-https.rule=Host(`traefik.fabianvolkers.com`)"
        - "traefik.http.routers.api-https.entrypoints=websecure"
        - "traefik.http.routers.api-https.tls=true"
        - "traefik.http.routers.api-https.service=api@internal"
        - "traefik.http.routers.api-https.tls.certresolver=le"
        - "traefik.http.services.api.loadbalancer.server.port=8080"


networks:
  traefik-public:
    external: true
